### ISSUE TITLE
Backup Directory (False positives) - Rails Forms v1.1

### ISSUE THREAD

**Issue by whithajess** [Arachni/arachni#547] opened 2015-02-15 23:12 UTC
Have a whole bunch off:

```
 [+] [272] Backup directory
 [~] ~~~~~~~~~~~~~~~~~~~~
 [~] Digest:     1185694936
 [~] Severity:   Medium

 [~] URL:        http://127.0.1.1:3000/testforms/771%20(third%20copy)/
 [~] Element:    server

 [~] Tags: path, backup, file, discovery

 [~] Description: 
 [~] 
A common practice when administering web applications is to create a copy/backup
of a particular directory prior to making any modification.
Another common practice is to add an extension or change the name of the original
directory to signify that it is a backup (examples include `.bak`, `.orig`, `.backup`,
etc.).

During the initial recon stages of an attack, cyber-criminals will attempt to
locate backup directories by adding common extensions onto directories already
discovered on the webserver. By analysing the response headers from the server
they are able to determine if a backup directory exists.
These backup directories can then assist in the compromise of the web application.

By utilising the same method, Arachni was able to discover a possible backup directory.
```

These responses come back as ok because off this:
```ruby
(byebug)  Testform.find("771%20(third%20copy)")
  Testform Load (0.2ms)  SELECT "testforms".* FROM "testforms" WHERE "testforms"."id" = $1 LIMIT 1  [["id", "771%20(third%20copy)"]]
#<Testform id: 771, formfield1: "1", formfield2: "1", formfield3: "1", created_at: "2015-02-12 23:02:28", updated_at: "2015-02-12 23:02:28">
(byebug) "771%20(third%20copy)".to_i
771
```

This may be a postgres specific implementation?

**Comment by Zapotek** [comment] 2015-02-15 23:30
Ah OK, I had fixed another FP issue having to do with Rails and the way it handles requests for file extensions without handlers but this is new to me.

It will be fixable though, just need to update the training scenarios for it.
Any chance you can setup a demo app that triggers this issue?

Cheers

**Comment by whithajess** [comment] 2015-02-15 23:31
Yeah no problems ill send you a link in a second when I get one setup.

**Comment by whithajess** [comment] 2015-02-16 00:00
https://github.com/whithajess/rails_form_tester

**Comment by whithajess** [comment] 2015-02-16 00:03
Also it seems non database specific that example app has an sqlite database, and before when I found the problem was on postgres

**Comment by Zapotek** [comment] 2015-02-16 00:07
Thanks a lot man, much appreciated. I'll keep this issue updated.

**Comment by Zapotek** [comment] 2015-02-17 20:00
Did you perform a scan against that app? Because I'm not getting anything. The forms aren't being listed, could this be the issue why I can't reproduce the FP?

**Comment by whithajess** [comment] 2015-02-17 21:10
Yeah I ran it against that app. And just for sanity again now I pulled the exact code from the github and ran it and it worked.

did you go through the start up instructions? (these are the exact ones I ran)
```ruby
RAILS_ENV=production rake db:create
RAILS_ENV=production rake db:migrate
RAILS_ENV=production bundle exec rake assets:precompile
RAILS_ENV=production rails s
```

I can upload my `.afr` file if that helps?

**Comment by Zapotek** [comment] 2015-02-17 21:12
Hm, could you show me the command you used to run the scan?

**Comment by whithajess** [comment] 2015-02-17 21:12
bin git:(v1.1) ✗ ./arachni http://192.168.0.23:3000/

**Comment by Zapotek** [comment] 2015-02-17 21:33
Great, worked this time, cheers. :)

**Comment by Zapotek** [comment] 2015-02-17 21:40
On the plus side, the issue is correctly marked as untrusted and the falsely logged resource is not fed back to the system for further analysis.
Now looking into how to take care of the root cause.

**Comment by Zapotek** [comment] 2015-02-17 22:04
Was a tiny bug after all. :)
It should be OK now.

Thanks for the feedback, much appreciated.

**Closed by Zapotek** 2015-02-17 22:04 UTC
