### ISSUE TITLE
Is there a way to dynamically add routes to search if whitebox testing?

### ISSUE THREAD

**Issue by nitrocode** [Arachni/arachni#796] opened 2016-11-11 20:41 UTC
Hi. I'm whitebox testing a company's application. Is there a way that I can manually (or programmatically) add relative routes to the url that I'm pointing arachni at?

FYI this is a single page application.

**Comment by Zapotek** [comment] 2016-11-12 16:21
I think there's a [feature request](https://github.com/Arachni/arachni/issues/776) open that would satisfy your requirement, is that right?

**Comment by nitrocode** [comment] 2016-11-14 19:46
Yes, you are correct. Since this feature does not currently exist, is there a way to manually add fragments?

**Comment by Zapotek** [comment] 2016-11-14 19:48
There's the `restrict_to_dom_state` plugin but it only allows you specify one fragment at the moment.

**Comment by Zapotek** [comment] 2016-11-15 10:03
Closing this as a duplicate of #776.

**Closed by Zapotek** 2016-11-15 10:03 UTC
