### ISSUE TITLE
plugin login_script does not load page

### ISSUE THREAD

**Issue by m6a-UdS** [Arachni/arachni#767] opened 2016-08-22 21:01 UTC
Hello,

I have some trouble recently with the login_script plugin: It does not load the page. Here is my  `login_script`:
> ret = browser.goto 'https://mywebsite.com'
> puts 'RET: ' + ret
> puts 'STATUS: ' + browser.status
> puts 'HTML: ' + browser.html
> form = browser.form( action: '/login/')
> form.text_field(name: 'username').set('someuser')
> form.text_field(name: 'password').set('`<XXX>`')
> 
> form.submit
> sleep(10)
> 
> framework.options.session.check_url     = browser.url
> framework.options.session.check_pattern = /logout/

Here is what I got as output:
> RET: about:blank
> STATUS:
> HTML: `<html><head></head><body></body></html>`

Notice that this started happening not long ago (about 3 of weeks max), nothing changed about the said website; It seems to me that the `login_script` stays stuck on `about:blank` and never executes the `browser.goto` instruction.

I was thinking about [this issue](http://stackoverflow.com/questions/26583409/watir-webdriver-phantomjs-and-urls-that-redirect-to-https) with PhantomJS (our SSL stack is managed by the Amazon Load Balancers, so it should not be outdated...) but I get from [this conversation](https://github.com/Arachni/arachni/issues/764) that it might not be the case.

I tried this with Ubuntu 14.04 and Kali 2.0

Any help appreciated, thank you!

EDIT: Also note that the same code works as "stand-alone" ruby, when browser is a normal `watir` browser.
UPDATE: Same result with the nightlies...

**Comment by Zapotek** [comment] 2016-08-23 08:20
Any chance I can give this a try myself?
You can send over the details in [private](mailto:tasos.laskos@arachni-scanner.com).

**Comment by m6a-UdS** [comment] 2016-08-23 19:52
Thank you for your help!

Unfortunately this website is not exposed to the Web, but from what I see from Wireshark, it might not matter: It seems from Wireshark that no requests actually ever gets out of my computers; It seems like the proxy tries to send a CONNECT request, but gets a `400 Bad Request` answer for every website I try... Already seen this? Also note that one of the two CONNECT requests is made over IPv6 `::1`...

**Comment by Zapotek** [comment] 2016-08-24 11:01
Must be an environmental thing, requests for the internal proxy shouldn't resolve to IPv6, they're all using `127.0.0.1`.
I'll try Kali, see if I can reproduce it.

**Comment by m6a-UdS** [comment] 2016-08-24 14:41
Were you able to reproduce? Could-it be an update coming from Kali / Ubuntu in the way networking is handled?

I will test on a fresh VM to see what happens...

**Comment by Zapotek** [comment] 2016-08-25 15:58
The networking thing makes sense but I haven't gotten around to it yet, I'm currently working on a different issue.

**Comment by Zapotek** [comment] 2016-08-26 09:22
Is the latest Kali version v2.0? The site reports the current version as 2016.1.

**Comment by m6a-UdS** [comment] 2016-08-26 13:28
Yes I think it's a "rolling" version that officially always stays at 2.0.
You can verify with `cat /etc/issue`

**Comment by Zapotek** [comment] 2016-08-26 18:16
Fair enough, I'll set it up and try it out.

About the networking thing, this can happen when you bind to `localhost` because IPv6 is now given preference, but that's why I specifically bind to `127.0.0.1`.
Should be interesting to debug.

**Comment by m6a-UdS** [comment] 2016-08-26 20:17
I disabled IPv6 on my Kali machine and still receive the `400: Bad Request` after the CONNECT instruction.

**Comment by Zapotek** [comment] 2016-08-27 14:33
I've set up Kali, any chance I can have a look at that website?
You can send over the info in [private](mailto:tasos.laskos@arachni-scanner.com) if you prefer.

**Comment by Zapotek** [comment] 2016-08-28 10:11
I just re-read your e-mail and noticed you mentioned that the site was private, but that you could also reproduce the issue by visiting: https://wiki.mozilla.org/index.php?title=Special:UserLogin&returnto=Main+Page

I just tried the same URL with the nightlies and they seem to work.

For example, try the following:

**browser.rb**
```ruby
Options.url = 'https://wiki.mozilla.org/index.php?title=Special:UserLogin&returnto=Main+Page'

b = Browser.new.watir

b.goto Options.url

puts b.html
```

Run with:

     bin/arachni_script browser.rb

It could be that the issue is fixed in the latest nightlies.

**Comment by m6a-UdS** [comment] 2016-08-29 15:04
Hello Zapotek,

Thanks you so much for helping me with this!

OMG, I just realized that this was an issue with my proxy! I am so sorry to have wasted your time on this! :-O I should have tested on a different network as I said!

Long story short, I make Arachni requests go through a ZAP Proxy and it's this part that was failing; Without it it works very well!

Thank you very much and sorry again for the false alarm! [#Code_18](http://www.urbandictionary.com/define.php?term=Code%2018) :-P

**Comment by Zapotek** [comment] 2016-08-29 15:06
No worries, it happens.

Cheers

**Closed by Zapotek** 2016-08-29 15:06 UTC
Labels: Bug, Experimental, Master
