### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by ZeroChaos-** [Arachni/arachni#809] opened 2016-12-19 21:26 UTC
Please, tag something new :-)  It's been a long time

**Comment by blshkv** [comment] 2016-12-20 02:04
It were no commits since Apr 21, 2016 so I doubt they can provide anything new

**Comment by ZeroChaos-** [comment] 2016-12-20 15:45
you should probably look harder, development is done in the experimental branch

https://github.com/Arachni/arachni/commits/experimental

**Comment by Zapotek** [comment] 2016-12-20 21:49
There is a blocker in a dependency and I'm waiting for it to get resolved.
After that I'll be able to release a new version.

**Comment by Zapotek** [comment] 2016-12-23 13:59
In case anyone's interested, this is the one: https://github.com/ohler55/ox/issues/158

**Comment by Zapotek** [comment] 2017-01-01 20:44
The bug has been fixed so a release will be made soon.

**Comment by Zapotek** [comment] 2017-01-12 11:49
The release announcement has been written, I'm now running final tests to ensure that I didn't miss any regressions.

**Comment by Zapotek** [comment] 2017-01-19 13:08
Unfortunately I found a couple of regressions, one has to do with a dependency; I've informed the maintainer and waiting for a fix.
The other won't be fixed in time for the release because the fix can't be adequately tested in time, the impact however will be minimal.

**Comment by Zapotek** [comment] 2017-01-31 13:25
Gem has been released, packages are being built.

**Closed by Zapotek** 2017-01-31 13:25 UTC

**Comment by Zapotek** [comment] 2017-01-31 15:52
Done: http://www.arachni-scanner.com/blog/arachni-framework-v1-5-webui-v0-5-11-release/

**Comment by ZeroChaos-** [comment] 2017-02-03 17:55
thank you, kind sir
