### ISSUE TITLE
[NoMethodError] undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by cclements** [Arachni/arachni#732] opened 2016-06-09 04:39 UTC
Got this during a scan with the latest nightly tonight:
https://gist.github.com/cclements/3c0deb5ca6ff38e514743eb4e2825988

**Comment by Zapotek** [comment] 2016-06-09 08:51
I'm flummoxed, judging by the code this error should be impossible.
Any chance I can have a look at the page?
It's a simple error, but I can't imagine the circumstances that would trigger it.

**Comment by Zapotek** [comment] 2016-08-03 14:49
Any update on this? Can I get a look at that page?

**Comment by Zapotek** [comment] 2016-08-08 09:12
I haven't managed to reproduce so I'm closing it for now.
Please re-open if you've got a test case for me.

Cheers

**Comment by cclements** [comment] 2016-08-26 19:35
Sorry for not getting back to you on this.  I just tried with the newest nightlies on testfire and got this error again:

https://gist.github.com/cclements/34a1ff681e5e1ee740447cc7e6f02910

I have no idea what's causing it, but /something/ is going on here.

**Comment by Zapotek** [comment] 2016-08-27 07:42
Turns out it's the `--audit-with-both-methods` option, I had missed it before.

**Comment by Zapotek** [comment] 2016-08-27 10:51
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up and include the fix.

**Closed by Zapotek** 2016-08-27 10:51 UTC
Labels: Bug, Experimental
