### ISSUE TITLE
Proxy error in cli output

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni#880] opened 2017-05-03 10:00 UTC
While using the proxy to record a login I noticed the following error.
```
#<NameError: undefined local variable or method `pages' for #<Arachni::Plugins::Proxy::TemplateScope:0x000000051cd090>>
[
    [ 0] "(erb):3:in `get_binding'",
    [ 1] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'",
    [ 2] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'",
    [ 3] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-16924dee2d64/components/plugins/proxy/template_scope.rb:106:in `erb'",
    [ 4] "(erb):64:in `get_binding'",
    [ 5] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'",
    [ 6] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'",
    [ 7] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-16924dee2d64/components/plugins/proxy/template_scope.rb:106:in `erb'",
    [ 8] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-16924dee2d64/components/plugins/proxy.rb:449:in `erb'",
    [ 9] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-16924dee2d64/components/plugins/proxy.rb:220:in `request_handler'",
    [10] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-16924dee2d64/lib/arachni/http/proxy_server/connection.rb:140:in `call'",
    [11] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-16924dee2d64/lib/arachni/http/proxy_server/connection.rb:140:in `handle_request'",
    [12] "/home/brian/Projects/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-16924dee2d64/lib/arachni/http/proxy_server/connection.rb:91:in `block (3 levels) in initialize'"
```

One of the templates not handling an input, perhaps?

**Comment by Zapotek** [comment] 2017-05-03 11:47
I can't reproduce it, what steps did you follow?

**Comment by bgerardw** [comment] 2017-05-03 15:50
>  ./arachni http://testfire.net --plugin=proxy

Then go to the panel at http://arachni.proxy/panel.

Then click the start recording button.

That gives me the following in the terminal.

Proxy: Requesting http://arachni.proxy/panel/record/start
#<NameError: undefined local variable or method `pages' for #<Arachni::Plugins::Proxy::TemplateScope:0x00000003df0090>>
[
    [ 0] "(erb):3:in `get_binding'",
    [ 1] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'",
    [ 2] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'",
    [ 3] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/gems/bundler/gems/arachni-54570d52a697/components/plugins/proxy/template_scope.rb:106:in `erb'",
    [ 4] "(erb):64:in `get_binding'",
    [ 5] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'",
    [ 6] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'",
    [ 7] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/gems/bundler/gems/arachni-54570d52a697/components/plugins/proxy/template_scope.rb:106:in `erb'",
    [ 8] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/gems/bundler/gems/arachni-54570d52a697/components/plugins/proxy.rb:449:in `erb'",
    [ 9] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/gems/bundler/gems/arachni-54570d52a697/components/plugins/proxy.rb:220:in `request_handler'",
    [10] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/gems/bundler/gems/arachni-54570d52a697/lib/arachni/http/proxy_server/connection.rb:140:in `call'",
    [11] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/gems/bundler/gems/arachni-54570d52a697/lib/arachni/http/proxy_server/connection.rb:140:in `handle_request'",
    [12] "/home/brian/Projects/arachni-2.0dev-1.0dev-old/system/gems/bundler/gems/arachni-54570d52a697/lib/arachni/http/proxy_server/connection.rb:91:in `block (3 levels) in initialize'"
]

**Comment by Zapotek** [comment] 2017-05-06 11:07
The fix is in the nightlies.

**Closed by Zapotek** 2017-05-06 11:07 UTC
