### ISSUE TITLE
Error in Arachni::Checks::UnvalidatedRedirectDOM: undefined method `with_browser' for nil:NilClass

### ISSUE THREAD

**Issue by cclements** [Arachni/arachni#719] opened 2016-05-17 01:09 UTC
https://gist.github.com/cclements/e304e1625b4d1437982002d5b3ca3336

**Comment by Zapotek** [comment] 2016-05-17 07:22
Were you using the latest nightlies?

**Comment by Zapotek** [comment] 2016-05-17 07:28
Judging by the log I'd say yes, is there any chance you can provide me with the target URL so that I can rerun the scan and try to reproduce the issue?

Cheers

**Comment by cclements** [comment] 2016-05-17 18:41
Yep, was the latest nightly.  It's an internal site, but I can likely get you access.  Do you need cli as well as access to the arachni web interface?

**Comment by Zapotek** [comment] 2016-05-17 18:42
If I could SSH and use the CLI along with maybe vim that'd be great.

**Comment by cclements** [comment] 2016-05-17 18:43
cool, we're firing up a container on our box for you.  will respond out of band with access details.

**Comment by Zapotek** [comment] 2016-05-17 18:44
Thanks a lot, I'll need to get to this tomorrow though.

**Comment by cclements** [comment] 2016-06-03 19:11
Got a public site I can repro this on if you'd like to check it out.

**Comment by Zapotek** [comment] 2016-06-04 08:01
Yes please.

**Comment by cclements** [comment] 2016-06-04 19:49
While troubleshooting this I think I narrowed it down to a setting in my scan profile.  In trying to isolate which setting was causing it, I modified my profile and started a new scan.  After about 15min the webui died and the console was spewing these logs:

```
::1 - - [04/Jun/2016:14:43:55 -0500] "GET /500 HTTP/1.1" 500 643 0.0316
::1 - - [04/Jun/2016:14:43:55 -0500] "GET /500?action=index&amp;controller=scans&amp;filter_active=yours&amp;filter_finished=yours&amp;filter_suspended=yours&amp;format=js HTTP/1.1" 500 643 0.0341

log writing failed. No such device or address @ io_write - D:\Downloads\arachni-2.0dev-1.0dev-windows-x86_64\system\\logs\webui/production.log

log writing failed. No such device or address @ io_write - D:\Downloads\arachni-2.0dev-1.0dev-windows-x86_64\system\\logs\webui/production.log

log writing failed. No such device or address @ io_write - D:\Downloads\arachni-2.0dev-1.0dev-windows-x86_64\system\\logs\webui/production.log
```


Do you think this is related or should I open a new issue (or ignore)?

**Comment by cclements** [comment] 2016-06-06 01:53
Found it.  This happens to me consistently when changing the request timeout from the default 10s to 20s.  Making that change is the difference between a scan of demo.testfire running successfully and it throwing this error.

**Comment by Zapotek** [comment] 2016-06-06 07:16
The default is 20 but I'll give the demo webapp a try.
About the WebUI, could you open a separate issue with reproduction instructions at: https://github.com/Arachni/arachni-ui-web/issues

**Comment by Zapotek** [comment] 2016-06-06 08:41
I may have gotten confused, you were talking about the last error right? Not the original?

**Comment by cclements** [comment] 2016-06-06 15:47
Sorry, to clarify, changing the request timeout to something like 20s is what seems to be causing the original error.  Let me see if I can repro the webui errors.  If so I'll open a new issue over on that repo.

**Comment by Zapotek** [comment] 2016-06-06 15:48
Timeout, right, I thought it said concurrency.
Can you paste the exact CLI config please?

**Comment by cclements** [comment] 2016-06-06 19:52
I'm going to be away for a few days, but literally the only changes between my profile and the default is the request timeout and the user agent.  I set that to:

Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko

**Comment by Zapotek** [comment] 2016-06-07 09:48
Nothing's happening, tried both CLI and WebUI.

**Comment by cclements** [comment] 2016-06-09 04:40
Strange.  I'll keep trying different things to see if I can narrow it down further.

**Comment by Zapotek** [comment] 2016-06-09 08:43
Thank you.

**Comment by Zapotek** [comment] 2016-08-08 09:14
Any update on this?

**Comment by Zapotek** [comment] 2016-08-24 12:11
I'm closing this, I can't reproduce it.
Let me know if you find a clear-cut test case I can try.

**Closed by Zapotek** 2016-08-24 12:11 UTC
Labels: Bug
