### ISSUE TITLE
Error in Arachni::Checks::LdapInjection: Invalid predicate: select[@name="\"template\""]

### ISSUE THREAD

**Issue by cclements** [Arachni/arachni#616] opened 2015-09-24 22:02 UTC
https://gist.github.com/cclements/98deda687e3998429b4c

This error causes scan traffic to cease, however, arachni still reports the scan is running.

**Comment by Zapotek** [comment] 2015-09-25 02:46
Duplicate of: https://github.com/Arachni/arachni/issues/615

**Closed by Zapotek** 2015-09-25 02:46 UTC
