### ISSUE TITLE
Arachni can't login on website due to cookies which get lost while trying to login through ADFS (visit 2 seperate sites to get back @ the actual site)

### ISSUE THREAD

**Issue by imdos** [Arachni/arachni#792] opened 2016-11-02 19:57 UTC
I am experiencing a [problem](http://support.arachni-scanner.com/discussions/problems/4134-arachni-cant-login-on-adfs-through-login_scriptor-proxy-since-it-does-not-store-cookies-from-intermediate-servers-during-login-process) with using the login_script. 

All content of the website is behind a login and it concerns a SiteCore implementation which is secured through ADFS with SAML. Full details are included in the above link. 

To access the site I get redirected to a portal. At the portal I have to select the identity provider (with a post to request) I would like to authorize against and then I get redirected to the actual login page in which the credentials are required. 
The login script fails at this step since Arachni won't use the Cookies it receives from the login site (not included in scope and on another domain {however it does honor the proper redirects; since I checked those with BurpSuite}). I have experienced the same behaviour with the Arachni proxy functionality. 

The problem is that I am unable to do proper authentication since the website looses track of the login session whilst the Cookies on those two sub-domains (on another domain) just aren't used at all. The Cookies are used flawlessly on the website I'm trying to test; but not on the domain not in scope. 

I have tested this with 1.4 and all the nightlies and included the redacted same error log and login script. To be sure I have included the scan template as well. Unfortunately I am unable to provide access since this is an internal test system (more systems to be tested!). 

Additional information is in the provided link and in the log files I have included. Please let me know should there be any information missing.

CMD:
`arachni-2.0dev-1.0dev/bin/arachni --profile-load-filepath=scan_profile.afp --plugin=script:script=arachni.login.rb https://URL/ --output-debug=4 --scope-exclude-pattern css,woff,ttf > error.log 2>&1`

[error.log.txt](https://github.com/Arachni/arachni/files/567531/error.log.txt)
[scan_profile.afp.txt](https://github.com/Arachni/arachni/files/567544/scan_profile.afp.txt)

[arachni.login.rb.txt](https://github.com/Arachni/arachni/files/567530/arachni.login.rb.txt)

**Comment by imdos** [comment] 2016-11-04 17:31
I have tried the same login sequence; this time with the proxy and I receive the message: "username or password incorrect" when I enter in the credentials. 

It appears though that the cookies do get collected but appear as part of the first hostname (arachni.scan.host) and not as part of the login.FQDN.redacted site. 
[test.log.txt](https://github.com/Arachni/arachni/files/572245/test.log.txt)

**Comment by Zapotek** [comment] 2016-11-05 09:56
You really shouldn't open an issue on every available portal, it makes it very cumbersome to track it.
If you believe this to be a bug please leave this ticket open and close the support discussion.

**Comment by imdos** [comment] 2016-11-07 20:01
Okay; I have tried to close the problem on your website; but that doesn't work. 

To comment on my issue. I have attached all logs I could think of with all the details and have only made some minor adjustments to the URL's and cookies. 

The problem/issue I'm experiencing is that with the login script I'm unable to properly login to the website I would like to test. For the login to work I have to get to the proper federated identity server. This is accomplished through:
1. Just visit the base path of the URL I would like to test 
2. Choose the right identity provider from the list on a portal website. 
3. Enter in the credentials on the login form (and don't forget to include the proper cookies; which doesn't work with Arachni login_script or proxy plugin or with irb and watir plus phantomjs). 

I tried both the nightlies up until those of today and the 1.4 stable branch. 

The best result I got up until now was through the proxy plugin; since there I noticed that the Cookies weren't trown away (they are received at line 412/413 in test.log.txt), but appear on the arachni.scan.host or portal.FQDN.redacted instead of the login.FQDN.redacted.

These Cookies are: "MSISIPSelectionSession" and this one contains the base64 encoded URI. And the other one is dynamic. In the case of test.log.txt it appears as: "MSISContextbe030a1a-7aea-4e2d-9d90-f7152977a5e7" or something similar and this latter section (GUID) is dependant on this parameter "wctx=be030a1a-7aea-4e2d-9d90-f7152977a5e7" (line 409). 

For some strange reason it seems impossible to just save the Cookies throughout the login process and reuse them in the next request (on the same host).

**Comment by Zapotek** [comment] 2016-11-08 09:07
Regarding the `login_script`, if vanilla Watir + PhantomJS didn't work then I'm afraid Arachni won't work either.
The proxy should have worked however, is thee a chance I can be granted access to the webapp with some demo credentials?

**Comment by imdos** [comment] 2016-11-08 13:31
I'm afraid I can't help you with access to this site. This is an internal server/environment. I will have a look tomorrow to see if I have a test site online for you to test.

**Comment by Zapotek** [comment] 2016-11-08 13:42
Much appreciated.

**Comment by imdos** [comment] 2016-11-10 08:32
Hi Tasos, I've searched hard to come up with an site which resembles the login behavior and we don't have any externally facing website with redirects. 

But there is onedrive from Microsoft which also works with WS-Federation. Here you visit www.onedrive.com which redirects you to: https://onedrive.live.com on which you have to enter your email address and your password on https://login.live.com/login.srf? etc. 

This can be tested with an (new or) existing hotmail.com or live.com email account AFAIK. I have just tested this with my own account.

**Comment by imdos** [comment] 2016-11-18 20:38
I almost got ik working; but due to unclear reasons it fails at checking the framework.options.session.check_url  or pattern. 

> [2016-11-18 16:51:44 +0100] Login script: [components/plugins/login_script#set_status:99] The script was executed successfully, but the login check failed.

This does work with curl:
"curl -v -i -b cookies.txt https://URL/welkom |grep -i something" this provides me with two entries of something (one is an h1 style).

Although I provide the cookies via various ways (run with exec:pre= or just before the cmd  with ./rubylogin.rb and login script). If I try to load my login_script from within arachni it bumps out because it can't find mechanize. If I use the --exec:pre="login_session.rb" it fails as well. 

How can I provide a logged in session (the cookies) to Arachni with the cmd's available?

This is my login_script
`http.cookie_jar.load 'cookies.txt'`

I had this as an option:
`login_script.rb; arachni --profile-load-filepath=profile.afp --http-cookie-jar cookies.txt --plugin=login_script:script=cookies.rb`
profile.afp contains the session checking.

And this is my working login script with Mechanize. 

```
#!/usr/bin/env ruby
require 'mechanize'
#require 'logger'
# Create a new mechanize object
a = Mechanize.new
#a.log = Logger.new "mechanize.log"
#a.log.level = Logger::DEBUG
#a.agent.http.debug_output = "mechanize.log"
# 'Windows IE 9'
a.user_agent_alias = 'Mac Safari'
a.follow_meta_refresh = true
a.redirect_ok = true
a.set_proxy('127.0.0.1', 3128)
#a.follow_redirect = true
page = a.get('https://URL/')
# portal
form1 = page.forms.first
form1["HomeRealmSelection"] = 'http://login.FQ.DN/adfs/services/trust'
page = a.submit(form1)
# Inloggen
form2 = page.form('aspnetForm')
form2["ctl00$ContentPlaceHolder1$UsernameTextBox"] = 'foo'
form2["ctl00$ContentPlaceHolder1$PasswordTextBox"] = 'bar'
form2["ctl00$ContentPlaceHolder1$SubmitButton"] = 'Sign In'
page = a.submit(form2)
# Dit is extra aangezien er JS in zit.
#<noscript><p>Script is disabled. Click Submit to continue.</p><input type="submit" value="Submit" /></noscript></form><script language="javascript">window.setTimeout('document.forms[0].submit()', 0);</script></body></html>
#POST SAML token naar login.
form3 = page.form('hiddenform')
page = a.submit(form3)
# en nu nog 1x
form4 = page.form_with(action: "https://URL:443/_trust")
form4.submit
fp = File.new("cookies.txt", "w")
#a.cookie_jar.save(fp, session: true)
a.cookie_jar.save_as(fp, :cookiestxt, :session => true)
fp.close
```

**Comment by Zapotek** [comment] 2016-11-20 17:05
You can try installing extra gems you need with:

    ./bin/arachni_shell -c"gem install mygem"

You may not be able to include it in your login script, however it should work with the `exec` plugin.
You really shouldn't have to go to all this trouble though, I'll try logging in to www.onedrive.com when I get a chance and see if I can get the problem solved for good.

**Comment by imdos** [comment] 2016-11-21 15:04
I've overcome the next hurdle; arachni doesn't like the ruby HTTP::Cookie nor the CURL Netscape style cookies.txt. 

```
# Dirty hack; strip alle niet benodigde regels en hou een
# Arachni approved Cookie (Netscape style Cookie-jar) over.
new_file = 'URL.cookies.txt'
old_file = "URLtempcookies.txt"
File.open new_file, 'w' do |file|
  File.foreach old_file do |line|
# 
# #HttpOnly_URL       FALSE   /adfs   TRUE    0       MSISAuthenticated       base64encoded
        file << line.gsub("\#HttpOnly_", "")
  end
end
File.delete(old_file)
```

The login check is successful now, but for some strange reason it doesn't work as expected. Is this because it doesn't update the cookies it receives? Or have I misconfigured somewhere. The only error I see is:

>  [2016-11-21 15:39:56 +0100 - 0.0] [!!!!] [http/client#global_on_complete:625] Client: ------------
>  [~] Ignoring page due to exclusion criteria:  

This is my scope 
`scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: [woff,tiff,gif,jpg,png,css,pdf,doc,docx,xls,xlsx,zip,rar]
  exclude_path_patterns: []
  exclude_content_patterns:
  - exit
  - logoff
  - logout
  - mailto
  - signoff
  - signout
  - uitloggen
  - Exit
  - Logoff
  - Logout
  - Mailto
  - Signoff
  - Signout
  - Uitloggen
  - 'Log uit'
  - 'log uit'
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
  include_subdomains: false
  exclude_binaries: false
  https_only: false
  auto_redundant_paths: 2
`

**Comment by imdos** [comment] 2016-11-24 16:33
I tuned the scope a bit and finally got Arachni working. Although not exactly as I wanted. In the meantime I managed to get it working outside of Arachni with plain watir (6.0.2)+phantomjs(executable from Arachni). I have tested the same within Arachni with the login_script and setting the proxy; but that failed at the same point. 

Therefore there could be something wrong with the version of watir-webdriver (v0.8.0 versus v0.9.9 "Watir 6.0"), which lacks support. Or there is something else going wrong within defining the scope. 

This is what I used in irb. 
```
require 'watir'
Selenium::WebDriver::PhantomJS.path = '/home/arachni/arachni-2.0dev-1.0dev/system/usr/bin/phantomjs'
browser = Watir::Browser.new( :phantomjs, args: '--proxy=localhost:3128' )
http_opts = {
             update_cookies:  true,
             follow_location: true,
             performer:       self
            }
browser.goto 'https://URL/'
# Wacht op het formulier v/d portal
browser.form.wait_until_present(:id => 'hrd')
browser.img(:alt => 'foobar').parent.click
# Wacht op het formulier met credentials
browser.form.wait_until_present(:id => 'aspnetForm')
browser.text_field(:id => 'ctl00_ContentPlaceHolder1_UsernameTextBox').set('foo')
browser.text_field(:id => 'ctl00_ContentPlaceHolder1_PasswordTextBox').set('bar')
browser.input(:id => 'ctl00_ContentPlaceHolder1_SubmitButton').click
# This is for checking what is happening
browser.cookies.save 'cookies.txt'
# Wacht totdat er is ingelogd op de website en alle benodigde cookies er zijn
browser.text_field(:title => 'Object moved').wait_until_present
# This is for checking what is happening
browser.url
```

**Comment by Zapotek** [comment] 2016-11-28 12:55
I just tried the experimental (nightly) branch on `https://login.live.com/login.srf` and it worked fine:

```ruby
browser.goto 'https://login.live.com/login.srf'

form = browser.form( name: 'f1' )
form.text_field( name: 'loginfmt' ).set 'tasos.laskos@gmail.com'
form.input( type: 'submit' ).click

Watir::Wait.until do
    browser.text_field( name: 'passwd' ).visible?
end

browser.text_field( name: 'passwd' ).set 'my password'
form.submit

framework.options.session.check_url     = 'https://account.microsoft.com/?refd=account.microsoft.com&refp=home-about-index'
framework.options.session.check_pattern = /Recent purchases/
```

**Comment by Zapotek** [comment] 2016-12-01 11:32
Closing since a workaround turned out to be available and because I couldn't reproduce the issue.

**Closed by Zapotek** 2016-12-01 11:32 UTC
Labels: Bug

**Comment by luoluo1987** [comment] 2018-02-13 04:13
I recently have the same issue, cookies are empty. The only difference is I use the chrome webdriver instead of the default one. I can see it logged in successfully from browser because it will open a brower and log in. But the session check was not using any cookies at all. Did you fix it already? 

http_opts = {
             update_cookies:  true,
             follow_location: true,
             performer:       self
            }
browser = Watir::Browser.new :chrome
browser.goto 'https://example.com/account/sign-in'
sleep(2)
form = browser.forms.first

print "Browser form : #{form}"

form.text_field( name: 'phoneEmailUsername' ).set '**'
form.text_field( name: 'phoneEmailUsername' ).focus()
# browser.fire_event(form.text_field( name: 'phoneEmailUsername'), :blur )
# form.text_field( name: 'phoneEmailUsername' ).blur()
form.text_field( name:'password' ).set '**'
form.text_field( name:'password' ).focus()
# form.text_field( name:'password' ).blur()
form.button( class: 'auth-button').click()
browser.cookies.save 'cookies.txt'
sleep(3)
# framework.options.session.check_url    = browser.url
# framework.options.session.check_pattern    = />Logout</
browser.cookies.save 'cookies.txt'
sleep(2)
