### ISSUE TITLE
check for weak HTTPS protocol and ciphers

### ISSUE THREAD

**Issue by deltay** [Arachni/arachni#715] opened 2016-05-10 08:56 UTC
I would be better if there is check for weak HTTPS  protocol(sslv2 sslv3 ) and ciphers(altorithm, key size etc)

**Comment by Zapotek** [comment] 2016-05-10 08:57
Duplicate of: https://github.com/Arachni/arachni/issues/452

**Closed by Zapotek** 2016-05-10 08:57 UTC
